SELECT e.nom AS emp, d.nom AS dpt
FROM
	"employes.csv" e,
	"departements.csv" d
WHERE e.dpt = d.idd;

[normal]
emp,dpt
"Hamish Fulton",Direction
"Coby Dennis","Comptabilité"
"Paki Stanley",RH
"Ray Atkins",Production
"Otto Gray",Achats
"Nell Hurst","Comptabilité"
"Gemma Calhoun",Direction
"Devin Bolton",Direction
"McKenzie Jensen",Direction
"Yoshio Short",Marketing
"Tana Dillard","Comptabilité"
"Rose Hancock",RH
"Kessie Simmons",Achats
"Kieran Weaver",Direction
"Guinevere Byers","Développement"
"Philip Whitney",Production
"Tatyana Becker",Administration
"Kenyon Hood",Recherche
"Brandon Travis",Achats
"Giacomo Case","Comptabilité"
"Hoyt Alston",Administration
"Oliver Lowe",Recherche
"Carly Casey",Marketing
"Garth Chen",Marketing
"Ray Tran",Administration
"Minerva Ray",Marketing
"Simon Oneill",Marketing
"Hyacinth Harris",Production
"Tana Thomas",Direction
"Olympia Gay",Exportations
"Clarke Christian","Développement"
"Jasper Griffin","Comptabilité"
"Ivy Carroll",Marketing
"Joelle Meyer",Achats
"Martin Cabrera","Développement"
"Diana Levy",Marketing
"Zenaida Ashley",RH
"Bruno Shepherd","Développement"
"Gemma Wells",Exportations
"Amir Wall","Comptabilité"
"Maxwell Trujillo",Achats
"Mollie Poole",Production
"Uta Lindsey",RH
"Elmo Harrington",Marketing
"Kelly Schneider",Marketing
"Vivian Gregory",Direction
"Dante Pena",Achats
"Clark Sanford",Production
"Melinda Lott",Administration
"Hiram Bullock","Comptabilité"
"Eliana Santos",Direction
"Diana Peterson",Recherche
"Yen Perez",Marketing
"Vernon Nieves",Recherche
"Honorato Bowman",Exportations
"Kerry Walton",Marketing
"Keelie Rosales","Comptabilité"
"Gregory Hunter",Production
"Destiny Love",RH
"Peter Steele",Marketing
"Ryan Hyde",Marketing
"Austin Mueller",Direction
"Forrest Harrison",Recherche
"Nichole Baldwin",Marketing
"Marshall Nguyen","Développement"
"Raphael Diaz",RH
"Alexander Sullivan",Administration
"Hedwig Macias",Exportations
"Montana Mathis","Développement"
"Fredericka Alexander",Direction
"Aristotle Lloyd",Exportations
"Clark Henson",Direction
"Rebecca Carson",Achats
"Kameko Short",Direction
"Patrick Carey",Production
"Clark Hensley",Marketing
"Deborah Noel",Exportations
"Kai Kim",Marketing
"Iris Mcbride",Direction
"Hop White",RH
"Kenneth Estrada","Comptabilité"
"Jillian Watson",Production
"Kirby Washington",RH
"Arden Lancaster",Marketing
"Clementine Santana",Marketing
"Bernard Rice","Développement"
"Thor Bush",Direction
"Ora Grimes",Recherche
"Amelia Bryant","Comptabilité"
"Heidi Vinson","Comptabilité"
"Yuli Pate","Développement"
"Kenyon Molina",Production
"Lillian Berg",Recherche
"Norman Murphy","Comptabilité"